name: Scrape Soccer Odds

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install playwright aiohttp fake_useragent tenacity boto3
          playwright install chromium
          playwright install-deps chromium
      
      - name: Get dates
        id: dates
        run: |
          echo "today=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "tomorrow=$(date -d '+1 day' +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "today_iso=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      
      - name: Scrape today's matches
        id: scrape_today
        continue-on-error: true
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p data
          python src/main.py scrape_upcoming \
            --sport football \
            --date ${{ steps.dates.outputs.today }} \
            --markets 1x2 \
            --headless \
            --file_path data/today.json \
            --format json \
            --concurrency_tasks 2
      
      - name: Scrape tomorrow's matches
        id: scrape_tomorrow
        continue-on-error: true
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python src/main.py scrape_upcoming \
            --sport football \
            --date ${{ steps.dates.outputs.tomorrow }} \
            --markets 1x2 \
            --headless \
            --file_path data/tomorrow.json \
            --format json \
            --concurrency_tasks 2
      
      - name: Merge and format output
        run: |
          python scripts/merge_odds.py
      
      - name: Upload to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: data/odds.json
          file_type: text
      
      - name: Summary
        run: |
          echo "### Odds Scrape Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Date: ${{ steps.dates.outputs.today_iso }}" >> $GITHUB_STEP_SUMMARY
          if [ -f data/odds.json ]; then
            MATCH_COUNT=$(cat data/odds.json | python -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('matches', [])))")
            echo "- Matches scraped: $MATCH_COUNT" >> $GITHUB_STEP_SUMMARY
          fi
